name: Linux Only

on:
  push:
    tags:
      - 'v*'

jobs:
  upload-release:

    runs-on: ubuntu-18.04
    needs: [build-linux]

    steps:
    - uses: actions/checkout@v1
    - name: create release
      id: create_release
      uses: actions/create-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false   
    - name: download artifacts
      uses: actions/download-artifact@v1
      with:
        name: uploads     
    - name: upload linux
      id: upload-linux
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./uploads/sioyek-release.zip
        asset_name: sioyek-release-linux.zip
        asset_content_type: application/zip                                         

  build-linux:

    runs-on: ubuntu-18.04

    steps:
    - name: Set up GCC
      uses: egor-tensin/setup-gcc@v1
      with:
        version: 9
        platform: x64
        
    - uses: actions/checkout@v2
      with:
            submodules: 'recursive'
            
    - name: Install libharfbuzz
      run: sudo apt install libharfbuzz-dev
      
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.14.2'

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}

      run: ./build_and_release.sh
      env:
        CC:   gcc-9
        CXX:  g++-9
    - name: upload linux artifact
      uses: actions/upload-artifact@v1
      with:
        name: uploads
        path: sioyek-release.zip        
