name: filesystem_test

on:
  push:
    tags:
      - 'fs*'
env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

jobs:
  build:
    runs-on: ubuntu-18.04
    #runs-on: ubuntu-latest
    

    steps:
    - name: Set up GCC
      uses: egor-tensin/setup-gcc@v1
      with:
        version: 9
        platform: x64
    - uses: actions/checkout@v2
    
    - name: Print Cpp Version
      run: g++ --version
      
    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}

      run: cxx filesystemtest.cpp -std=c++17
      env:
        CC:   gcc-9
        CXX:  g++-9


