name: linux_release

on: push
env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

jobs:
  build:
    runs-on: ubuntu-latest
    #runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
      with:
            submodules: 'recursive'
    
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      
    - name: Install libharfbuzz
      run: sudo apt install libharfbuzz-dev

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}

      run: ./build_and_release.sh
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
          files: sioyek-release.zip
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
